// This slice manages the state for the contact form submission process.

// It handles the asynchronous submission action and updates status and error messages accordingly.
import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

// define the shape of the contact form data
export interface ContactFormData {
  fullName: string;
  phoneNumber: string;
  email: string;
  subject: string;
  message: string;
}

// define the shape of the contact slice state
interface ContactState {
  status: "idle" | "loading" | "succeeded" | "failed";
  error: string | null;
}

// initial state for the contact slice
const initialState: ContactState = {
  status: "idle",
  error: null,
};

// asynchronous thunk action for submitting the contact form
export const submitContactForm = createAsyncThunk(
  "contact/submit",
  async (data: ContactFormData) => {
    // simulate an API call with a delay
    await new Promise((resolve) => setTimeout(resolve, 1200));
    return data;
  }
);

// create the contact slice
const contactSlice = createSlice({
  name: "contact",
  initialState,
  reducers: {
    resetStatus(state) {
      state.status = "idle";
      state.error = null;
    },
  },
  // handle actions generated by the submitContactForm thunk
  extraReducers: (builder) => {
    builder
    // handle pending, fulfilled, and rejected states
      .addCase(submitContactForm.pending, (state) => {
        state.status = "loading";
      })
      .addCase(submitContactForm.fulfilled, (state) => {
        state.status = "succeeded";
      })
      .addCase(submitContactForm.rejected, (state) => {
        state.status = "failed";
        state.error = "Failed to send message";
      });
  },
});

// export the actions and reducer
export const { resetStatus } = contactSlice.actions;
export default contactSlice.reducer;
