// This file defines the Redux slice for managing projects data, including fetching projects and filtering by technology.

// It uses Redux Toolkit to create the slice and handle asynchronous actions.
import { createAsyncThunk, createSlice, type PayloadAction } from "@reduxjs/toolkit";


// define the shape of a project
export interface Project {
  liveUrl: string;
  id: string;
  title: string;
  tech: string;
  image: string;
  description: string;
}

// define the shape of the projects slice state
interface ProjectsState {
  items: Project[];
  filtered: Project[];
  selectedTech: string;
  status: "idle" | "loading" | "succeeded" | "failed";
  error: string | null;
}

// initial state for the projects slice
const initialState: ProjectsState = {
  items: [],
  filtered: [],
  selectedTech: "All",
  status: "idle",
  error: null,
};


// asynchronous thunk action for fetching projects data
export const fetchProjects = createAsyncThunk(
  "projects/fetchProjects",
  async () => {
    // fetch projects from a local JSON file
    const response = await fetch("/data/projects.json");

    // handle responses that are not valid
    if (!response.ok) {
      throw new Error("Failed to fetch projects");
    }

    // parse and return the JSON data as an array of Project
    return (await response.json()) as Project[];
  }
);

// create the projects slice
const projectsSlice = createSlice({
  name: "projects",
  initialState,
  reducers: {
    // reducer to filter projects by technology
    filterByTech(state, action: PayloadAction<string>) {
      state.selectedTech = action.payload;

      // filter projects based on the selected technology
      state.filtered =
        action.payload === "All"
          ? state.items
          : state.items.filter(
              (project) => project.tech === action.payload
            );
    },
  },
  // handle actions generated by the fetchProjects thunk
  extraReducers: (builder) => {
    builder
    // handle pending, fulfilled, and rejected states
      .addCase(fetchProjects.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchProjects.fulfilled, (state, action) => {
        state.status = "succeeded";
        state.items = action.payload;
        state.filtered = action.payload;
      })
      .addCase(fetchProjects.rejected, (state, action) => {
        state.status = "failed";
        state.error = action.error.message ?? "Something went wrong";
      });
  },
});

// export the actions and reducer
export const { filterByTech } = projectsSlice.actions;
export default projectsSlice.reducer;


